[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "phyphox-py"
version = "0.0.3"
authors = [
  { name="Laurent Berger", email="laurent.berger@univ-lemans.fr" },
]
description = "Python API for phyphox phone application"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {text = "LICEN[CS]E*"}

[project.urls]
Homepage = "https://github.com/LaurentBerger/phyphox-py"
Issues = "https://github.com/LaurentBerger/phyphox-py/issues"
